# Generated by Django 4.2.11 on 2024-03-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_testcase_answer_timestamp_testcase_is_answered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reload_time', models.IntegerField()),
            ],
        ),
    ]
