# Generated by Django 4.2.11 on 2024-03-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='sum_timestamp',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
